force-app/main/default/objects/ContactUsContact__c/ContactUsContact__c.object-meta.xml
<CustomObject>
    <description>This object holds all the ContactUsContact records based on the district/branch codes</description>
    <label>Contact Us Contact</label>
    <nameField>
        <label>Contact Us Contact Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Us Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactUsContact__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>To store the category values</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Federal Reserve Bank Services Support Center – FedLine&lt;sup&gt;®&lt;/sup&gt; Solutions</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Account Services</fullName>
            </value>
            <value>
                <fullName>Account Services Contacts</fullName>
            </value>
            <value>
                <fullName>Central Bank</fullName>
            </value>
            <value>
                <fullName>Discount Window</fullName>
            </value>
            <value>
                <fullName>FedCash&amp;reg; Services</fullName>
            </value>
            <value>
                <fullName>FedNow&amp;reg; Service</fullName>
            </value>
            <value>
                <fullName>Fedwire Funds and Fedwire Securities</fullName>
            </value>
            <value>
                <fullName>Local Federal Reserve Bank</fullName>
            </value>
            <value>
                <fullName>National Settlement Service</fullName>
            </value>
            <value>
                <fullName>Treasury Services</fullName>
            </value>
            <value>
                <fullName>Relationship Manager</fullName>
            </value>
            <value>
                <fullName>FedACH&amp;reg; and Check Services Contacts</fullName>
            </value>
            <value>
                <fullName>Treasury Services Contacts</fullName>
            </value>
            <value>
                <fullName>FedACH and Check Services</fullName>
            </value>
            <value>
                <fullName>FedACH&amp;reg; and Check Services</fullName>
                <isActive>false</isActive>
                <label>FedACH and Check Services</label>
            </value>
            <value>
                <fullName>FedCash Services</fullName>
                <isActive>false</isActive>
                <label>FedCash Services</label>
            </value>
            <value>
                <fullName>FedNow Service</fullName>
                <isActive>false</isActive>
                <label>FedNow Service</label>
            </value>
            <value>
                <fullName>Fedwire&amp;reg; Funds and Fedwire Securities</fullName>
                <isActive>false</isActive>
                <label>Fedwire&amp;reg; Funds and Fedwire Securities</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactUsContact__c/fields/Clone_Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Clone_Source_Id__c</fullName>
    <description>Contains the old original ContactUsContact record ID for the clone the clone record</description>
    <label>Clone Source Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContactUsContact__c/fields/Return_completed_original_docs_to__c.field-meta.xml
<CustomField>
    <fullName>Return_completed_original_docs_to__c</fullName>
    <inlineHelpText>Return completed original document(s) to</inlineHelpText>
    <label>Return completed original document(s) to</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ContactUsContact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Preview</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactUsContact__c/fields/SubCategory__c.field-meta.xml
<CustomField>
    <fullName>SubCategory__c</fullName>
    <label>SubCategory</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account Confirmation Request</fullName>
            </value>
            <value>
                <fullName>Account Open Coordinators</fullName>
            </value>
            <value>
                <fullName>Account Services Customer Support</fullName>
            </value>
            <value>
                <fullName>Billing Operations Site and Service Charge Information</fullName>
            </value>
            <value>
                <fullName>Board Resolutions/Official Authorization List</fullName>
            </value>
            <value>
                <fullName>Canadian Check Processing</fullName>
            </value>
            <value>
                <fullName>Capital Stock</fullName>
            </value>
            <value>
                <fullName>FedACH and Check Services Customer Support</fullName>
            </value>
            <value>
                <fullName>FedLine&amp;reg; Services Technical Support</fullName>
            </value>
            <value>
                <fullName>FedLine Solutions Set-up</fullName>
            </value>
            <value>
                <fullName>Foreign Check Processing</fullName>
            </value>
            <value>
                <fullName>General Inquiries</fullName>
            </value>
            <value>
                <fullName>Image-enabled Savings Bonds Processing</fullName>
            </value>
            <value>
                <fullName>Mergers</fullName>
            </value>
            <value>
                <fullName>Paper Check Adjustments and Supporting Documentation Processing</fullName>
            </value>
            <value>
                <fullName>Paper Check Processing</fullName>
            </value>
            <value>
                <fullName>Discount Window</fullName>
            </value>
            <value>
                <fullName>Credit Risk Management</fullName>
            </value>
            <value>
                <fullName>Excess Balance Account</fullName>
            </value>
            <value>
                <fullName>Reporting Central</fullName>
            </value>
            <value>
                <fullName>Reserves Central</fullName>
            </value>
            <value>
                <fullName>Term Deposit Facility</fullName>
            </value>
            <value>
                <fullName>FedACH and Check Services</fullName>
            </value>
            <value>
                <fullName>FedACH and Check Services Set-up</fullName>
            </value>
            <value>
                <fullName>Fedwire Funds and Fedwire Securities</fullName>
            </value>
            <value>
                <fullName>Separately Sorted Savings Bonds Processing</fullName>
            </value>
            <value>
                <fullName>Customer Support for Image-enabled Savings Bonds (provided by Federal Reserve Bank Services Support Center)</fullName>
            </value>
            <value>
                <fullName>Savings Bond Customer Support Contacts</fullName>
            </value>
            <value>
                <fullName>TCMM Operations Support</fullName>
            </value>
            <value>
                <fullName>National Settlement Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactUsContactTriggerTest.cls
@isTest
public class ContactUsContactTriggerTest {

    @TestSetup
    static void setupData() {
        ContactUsContact__c contact1 = new ContactUsContact__c();
        contact1.Description__c = 'test1';
        contact1.Status__c = 'Approved';
        contact1.Category__c = 'Account Executive';
        //contact1.SubCategory__c = 'Foreign Check Processing';
        contact1.Email__c = 'ccc.coordinators@kc.frb.org';
        contact1.Phone__c = '(833) 377-7820';
        contact1.Status__c = 'Approved';
        contact1.Return_completed_original_docs_to__c = 'National Accounting Customer Support';
        insert contact1;
    }
    
    @isTest
    public static void testBeforeInsert_setIsCloneToTrue_whenUserCloneRecord(){
        ContactUsContact__c con = [SELECT Id FROM ContactUsContact__c LIMIT 1];
        ContactUsContact__c cloneRecord = con.clone();
        cloneRecord.Status__c = 'Approved';
        
        Test.startTest();
        insert cloneRecord;
        Test.stopTest();
        
        cloneRecord = [SELECT Id, Is_Clone__c, Clone_Source_Id__c FROM ContactUsContact__c WHERE Id = :cloneRecord.Id];
        Assert.areEqual(true, cloneRecord.Is_Clone__c);
        Assert.areEqual(con.Id, cloneRecord.Clone_Source_Id__c);
    }
    
    @isTest
    public static void testBeforeInsert_itThrowError_whenUserTryToCloneAlreadyCloneRecord(){
        ContactUsContact__c con = [SELECT Id FROM ContactUsContact__c LIMIT 1];
        
        ContactUsContact__c cloneRecord = con.clone();
        cloneRecord.Status__c = 'Approved';
        insert cloneRecord;
        
        cloneRecord = [SELECT Is_Clone__c, Clone_Source_Id__c FROM ContactUsContact__c WHERE Id = :cloneRecord.Id];
        String err = '';
        
        Test.startTest();
        try{
            ContactUsContact__c duplicateClone = cloneRecord.clone();
            insert duplicateClone;
        }catch(Exception e){
            err = e.getMessage();
        }
        Test.stopTest();
        
        Assert.areEqual(true, err.contains('You cannot clone of already clone record.'));
    }
    
     @isTest
    public static void testBeforeUpdate_itThrowError_whenUserTryToUpdateRecord(){
        ContactUsContact__c con = [SELECT Id FROM ContactUsContact__c LIMIT 1];
        String err = '';
        
        Test.startTest();
        try{
            con.Description__c = 'test';
            update con;
        }catch(Exception e){
            err = e.getMessage();
        }
        Test.stopTest();
        
        Assert.areEqual(true, err.contains('You can only clone record to update the value and then submit for approval.'));
    }
    
    @isTest
    public static void testBeforeUpdate_itThrowError_whenUserTryToUpdateCloneRecordStatus(){
        ContactUsContact__c con = [SELECT Id FROM ContactUsContact__c LIMIT 1];
        ContactUsContact__c cloneRecord = con.clone();
        cloneRecord.Status__c = 'Approved';
        insert cloneRecord;
        
        // clone record submit for approval the status field set to 'Preview'
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(cloneRecord.id);
        Approval.ProcessResult result = Approval.process(app);
        
        String err = '';
        
        Test.startTest();
        try{
            cloneRecord.Status__c = 'Approved';
            update cloneRecord;
        }catch(Exception e){
            err = e.getMessage();
        }
        Test.stopTest();
        
        Assert.areEqual(true, err.contains('You cannot update clone record status field. It will get update by approval process.'));
    }
    
     @isTest
    public static void testAfterUpdate_itDeleteCloneRecord_whenCloneRecordIsApproved(){
        ContactUsContact__c con = [SELECT Id FROM ContactUsContact__c LIMIT 1];
        ContactUsContact__c cloneRecord = con.clone();
        cloneRecord.Status__c = 'Approved';
        insert cloneRecord;
        
        
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(cloneRecord.id);
        Approval.ProcessResult result = Approval.process(app);

        List<Id> newWorkItemIds = result.getNewWorkitemIds();

        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        req2.setWorkitemId(newWorkItemIds.get(0));
        
        // Submit the request for approval
        Approval.ProcessResult result2 =  Approval.process(req2);
                
        List<ContactUsContact__c> cloneRecordList = [SELECT Id FROM ContactUsContact__c WHERE Id = :cloneRecord.Id];
        System.assert(true, cloneRecordList.size() == 0);
        System.assert(true, result2.isSuccess());
    }
    
}